package orders_v0

import (
	"github.com/bytedance/sonic"
)

// checks if the AutomatedShippingSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AutomatedShippingSettings{}

// AutomatedShippingSettings Contains information regarding the Shipping Settings Automation program, such as whether the order's shipping settings were generated automatically, and what those settings are.
type AutomatedShippingSettings struct {
	// When true, this order has automated shipping settings generated by Amazon. This order could be identified as an SSA order.
	HasAutomatedShippingSettings *bool `json:"HasAutomatedShippingSettings,omitempty"`
	// Auto-generated carrier for SSA orders.
	AutomatedCarrier *string `json:"AutomatedCarrier,omitempty"`
	// Auto-generated ship method for SSA orders.
	AutomatedShipMethod *string `json:"AutomatedShipMethod,omitempty"`
}

// NewAutomatedShippingSettings instantiates a new AutomatedShippingSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAutomatedShippingSettings() *AutomatedShippingSettings {
	this := AutomatedShippingSettings{}
	return &this
}

// NewAutomatedShippingSettingsWithDefaults instantiates a new AutomatedShippingSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAutomatedShippingSettingsWithDefaults() *AutomatedShippingSettings {
	this := AutomatedShippingSettings{}
	return &this
}

// GetHasAutomatedShippingSettings returns the HasAutomatedShippingSettings field value if set, zero value otherwise.
func (o *AutomatedShippingSettings) GetHasAutomatedShippingSettings() bool {
	if o == nil || IsNil(o.HasAutomatedShippingSettings) {
		var ret bool
		return ret
	}
	return *o.HasAutomatedShippingSettings
}

// GetHasAutomatedShippingSettingsOk returns a tuple with the HasAutomatedShippingSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutomatedShippingSettings) GetHasAutomatedShippingSettingsOk() (*bool, bool) {
	if o == nil || IsNil(o.HasAutomatedShippingSettings) {
		return nil, false
	}
	return o.HasAutomatedShippingSettings, true
}

// HasHasAutomatedShippingSettings returns a boolean if a field has been set.
func (o *AutomatedShippingSettings) HasHasAutomatedShippingSettings() bool {
	if o != nil && !IsNil(o.HasAutomatedShippingSettings) {
		return true
	}

	return false
}

// SetHasAutomatedShippingSettings gets a reference to the given bool and assigns it to the HasAutomatedShippingSettings field.
func (o *AutomatedShippingSettings) SetHasAutomatedShippingSettings(v bool) {
	o.HasAutomatedShippingSettings = &v
}

// GetAutomatedCarrier returns the AutomatedCarrier field value if set, zero value otherwise.
func (o *AutomatedShippingSettings) GetAutomatedCarrier() string {
	if o == nil || IsNil(o.AutomatedCarrier) {
		var ret string
		return ret
	}
	return *o.AutomatedCarrier
}

// GetAutomatedCarrierOk returns a tuple with the AutomatedCarrier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutomatedShippingSettings) GetAutomatedCarrierOk() (*string, bool) {
	if o == nil || IsNil(o.AutomatedCarrier) {
		return nil, false
	}
	return o.AutomatedCarrier, true
}

// HasAutomatedCarrier returns a boolean if a field has been set.
func (o *AutomatedShippingSettings) HasAutomatedCarrier() bool {
	if o != nil && !IsNil(o.AutomatedCarrier) {
		return true
	}

	return false
}

// SetAutomatedCarrier gets a reference to the given string and assigns it to the AutomatedCarrier field.
func (o *AutomatedShippingSettings) SetAutomatedCarrier(v string) {
	o.AutomatedCarrier = &v
}

// GetAutomatedShipMethod returns the AutomatedShipMethod field value if set, zero value otherwise.
func (o *AutomatedShippingSettings) GetAutomatedShipMethod() string {
	if o == nil || IsNil(o.AutomatedShipMethod) {
		var ret string
		return ret
	}
	return *o.AutomatedShipMethod
}

// GetAutomatedShipMethodOk returns a tuple with the AutomatedShipMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AutomatedShippingSettings) GetAutomatedShipMethodOk() (*string, bool) {
	if o == nil || IsNil(o.AutomatedShipMethod) {
		return nil, false
	}
	return o.AutomatedShipMethod, true
}

// HasAutomatedShipMethod returns a boolean if a field has been set.
func (o *AutomatedShippingSettings) HasAutomatedShipMethod() bool {
	if o != nil && !IsNil(o.AutomatedShipMethod) {
		return true
	}

	return false
}

// SetAutomatedShipMethod gets a reference to the given string and assigns it to the AutomatedShipMethod field.
func (o *AutomatedShippingSettings) SetAutomatedShipMethod(v string) {
	o.AutomatedShipMethod = &v
}

func (o AutomatedShippingSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HasAutomatedShippingSettings) {
		toSerialize["HasAutomatedShippingSettings"] = o.HasAutomatedShippingSettings
	}
	if !IsNil(o.AutomatedCarrier) {
		toSerialize["AutomatedCarrier"] = o.AutomatedCarrier
	}
	if !IsNil(o.AutomatedShipMethod) {
		toSerialize["AutomatedShipMethod"] = o.AutomatedShipMethod
	}
	return toSerialize, nil
}

type NullableAutomatedShippingSettings struct {
	value *AutomatedShippingSettings
	isSet bool
}

func (v NullableAutomatedShippingSettings) Get() *AutomatedShippingSettings {
	return v.value
}

func (v *NullableAutomatedShippingSettings) Set(val *AutomatedShippingSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableAutomatedShippingSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableAutomatedShippingSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAutomatedShippingSettings(val *AutomatedShippingSettings) *NullableAutomatedShippingSettings {
	return &NullableAutomatedShippingSettings{value: val, isSet: true}
}

func (v NullableAutomatedShippingSettings) MarshalJSON() ([]byte, error) {
	return sonic.Marshal(v.value)
}

func (v *NullableAutomatedShippingSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return sonic.Unmarshal(src, &v.value)
}
