package replenishment20221107

import (
	"github.com/bytedance/sonic"
)

// checks if the GetSellingPartnerMetricsResponseMetric type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSellingPartnerMetricsResponseMetric{}

// GetSellingPartnerMetricsResponseMetric An object which contains metric data for a selling partner.
type GetSellingPartnerMetricsResponseMetric struct {
	// The percentage of items that were not shipped out of the total shipped units over a period of time due to being out of stock. Applicable to PERFORMANCE timePeriodType.
	NotDeliveredDueToOOS *float64 `json:"notDeliveredDueToOOS,omitempty"`
	// The revenue generated from subscriptions over a period of time. Applicable for both the PERFORMANCE and FORECAST timePeriodType.
	TotalSubscriptionsRevenue *float64 `json:"totalSubscriptionsRevenue,omitempty"`
	// The number of units shipped to the subscribers over a period of time. Applicable for both the PERFORMANCE and FORECAST timePeriodType.
	ShippedSubscriptionUnits *float32 `json:"shippedSubscriptionUnits,omitempty"`
	// The number of active subscriptions present at the end of the period. Applicable to PERFORMANCE timePeriodType.
	ActiveSubscriptions *float32 `json:"activeSubscriptions,omitempty"`
	// The average revenue per subscriber of the program over a period of past 12 months for sellers and 6 months for vendors. Applicable to PERFORMANCE timePeriodType.
	SubscriberAverageRevenue *float64 `json:"subscriberAverageRevenue,omitempty"`
	// The average revenue per non-subscriber of the program over a period of past 12 months for sellers and 6 months for vendors. Applicable to PERFORMANCE timePeriodType.
	NonSubscriberAverageRevenue *float64 `json:"nonSubscriberAverageRevenue,omitempty"`
	// The revenue that would have been generated had there not been out of stock. Applicable to PERFORMANCE timePeriodType.
	LostRevenueDueToOOS *float64 `json:"lostRevenueDueToOOS,omitempty"`
	// The average reorders per subscriber of the program over a period of 12 months. Applicable to PERFORMANCE timePeriodType.
	SubscriberAverageReorders *float64 `json:"subscriberAverageReorders,omitempty"`
	// The average reorders per non-subscriber of the program over a period of past 12 months. Applicable to PERFORMANCE timePeriodType.
	NonSubscriberAverageReorders *float64 `json:"nonSubscriberAverageReorders,omitempty"`
	// The percentage of revenue from ASINs with coupons out of total revenue from all ASINs. Applicable to PERFORMANCE timePeriodType.
	CouponsRevenuePenetration *float64 `json:"couponsRevenuePenetration,omitempty"`
	// The subscription revenue generated from subscriptions with over two deliveries over the past 12 months. Applicable to PERFORMANCE timePeriodType.
	RevenueFromSubscriptionsWithMultipleDeliveries *float64 `json:"revenueFromSubscriptionsWithMultipleDeliveries,omitempty"`
	// The subscription revenue generated from active subscriptions with one delivery over the past 12 months. Applicable to PERFORMANCE timePeriodType.
	RevenueFromActiveSubscriptionsWithSingleDelivery *float64 `json:"revenueFromActiveSubscriptionsWithSingleDelivery,omitempty"`
	// The subscription revenue generated from subscriptions which are cancelled after one delivery over the past 12 months. Applicable to PERFORMANCE timePeriodType.
	RevenueFromCancelledSubscriptionsAfterSingleDelivery *float64 `json:"revenueFromCancelledSubscriptionsAfterSingleDelivery,omitempty"`
	// The percentage of subscriptions retained after 30 days of subscription creation. Applicable to PERFORMANCE timePeriodType.
	SubscriberRetentionFor30Days *float64 `json:"subscriberRetentionFor30Days,omitempty"`
	// The percentage of subscriptions retained after 90 days of subscription creation. Applicable to PERFORMANCE timePeriodType.
	SubscriberRetentionFor90Days *float64 `json:"subscriberRetentionFor90Days,omitempty"`
	// The percentage of subscription revenue generated by offers with 0% seller-funded discount over the last 12 months. Applicable to PERFORMANCE timePeriodType.
	RevenuePenetrationFor0PercentSellerFunding *float64 `json:"revenuePenetrationFor0PercentSellerFunding,omitempty"`
	// [Applicable only for Sellers] The percentage of subscription revenue generated by offers with 5% seller-funded discount over the last 12 months. Applicable to PERFORMANCE timePeriodType.
	RevenuePenetrationFor5PercentSellerFunding *float64 `json:"revenuePenetrationFor5PercentSellerFunding,omitempty"`
	// [Applicable only for Sellers] The percentage of subscription revenue generated by offers with 10% seller-funded discount over the last 12 months. Applicable to PERFORMANCE timePeriodType.
	RevenuePenetrationFor10PercentSellerFunding *float64 `json:"revenuePenetrationFor10PercentSellerFunding,omitempty"`
	// [Applicable only for vendors] The percentage of subscription revenue generated by offers with 5% or above seller-funded discount over the last 12 months. Applicable to PERFORMANCE timePeriodType.
	RevenuePenetrationFor5PlusPercentSellerFunding *float64 `json:"revenuePenetrationFor5PlusPercentSellerFunding,omitempty"`
	// The percentage of new subscriptions acquired through coupons. Applicable to PERFORMANCE timePeriodType.
	ShareOfCouponSubscriptions *float64      `json:"shareOfCouponSubscriptions,omitempty"`
	TimeInterval               *TimeInterval `json:"timeInterval,omitempty"`
	// The currency code in ISO 4217 format.
	CurrencyCode *string `json:"currencyCode,omitempty"`
}

// NewGetSellingPartnerMetricsResponseMetric instantiates a new GetSellingPartnerMetricsResponseMetric object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSellingPartnerMetricsResponseMetric() *GetSellingPartnerMetricsResponseMetric {
	this := GetSellingPartnerMetricsResponseMetric{}
	return &this
}

// NewGetSellingPartnerMetricsResponseMetricWithDefaults instantiates a new GetSellingPartnerMetricsResponseMetric object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSellingPartnerMetricsResponseMetricWithDefaults() *GetSellingPartnerMetricsResponseMetric {
	this := GetSellingPartnerMetricsResponseMetric{}
	return &this
}

// GetNotDeliveredDueToOOS returns the NotDeliveredDueToOOS field value if set, zero value otherwise.
func (o *GetSellingPartnerMetricsResponseMetric) GetNotDeliveredDueToOOS() float64 {
	if o == nil || IsNil(o.NotDeliveredDueToOOS) {
		var ret float64
		return ret
	}
	return *o.NotDeliveredDueToOOS
}

// GetNotDeliveredDueToOOSOk returns a tuple with the NotDeliveredDueToOOS field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsResponseMetric) GetNotDeliveredDueToOOSOk() (*float64, bool) {
	if o == nil || IsNil(o.NotDeliveredDueToOOS) {
		return nil, false
	}
	return o.NotDeliveredDueToOOS, true
}

// HasNotDeliveredDueToOOS returns a boolean if a field has been set.
func (o *GetSellingPartnerMetricsResponseMetric) HasNotDeliveredDueToOOS() bool {
	if o != nil && !IsNil(o.NotDeliveredDueToOOS) {
		return true
	}

	return false
}

// SetNotDeliveredDueToOOS gets a reference to the given float64 and assigns it to the NotDeliveredDueToOOS field.
func (o *GetSellingPartnerMetricsResponseMetric) SetNotDeliveredDueToOOS(v float64) {
	o.NotDeliveredDueToOOS = &v
}

// GetTotalSubscriptionsRevenue returns the TotalSubscriptionsRevenue field value if set, zero value otherwise.
func (o *GetSellingPartnerMetricsResponseMetric) GetTotalSubscriptionsRevenue() float64 {
	if o == nil || IsNil(o.TotalSubscriptionsRevenue) {
		var ret float64
		return ret
	}
	return *o.TotalSubscriptionsRevenue
}

// GetTotalSubscriptionsRevenueOk returns a tuple with the TotalSubscriptionsRevenue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsResponseMetric) GetTotalSubscriptionsRevenueOk() (*float64, bool) {
	if o == nil || IsNil(o.TotalSubscriptionsRevenue) {
		return nil, false
	}
	return o.TotalSubscriptionsRevenue, true
}

// HasTotalSubscriptionsRevenue returns a boolean if a field has been set.
func (o *GetSellingPartnerMetricsResponseMetric) HasTotalSubscriptionsRevenue() bool {
	if o != nil && !IsNil(o.TotalSubscriptionsRevenue) {
		return true
	}

	return false
}

// SetTotalSubscriptionsRevenue gets a reference to the given float64 and assigns it to the TotalSubscriptionsRevenue field.
func (o *GetSellingPartnerMetricsResponseMetric) SetTotalSubscriptionsRevenue(v float64) {
	o.TotalSubscriptionsRevenue = &v
}

// GetShippedSubscriptionUnits returns the ShippedSubscriptionUnits field value if set, zero value otherwise.
func (o *GetSellingPartnerMetricsResponseMetric) GetShippedSubscriptionUnits() float32 {
	if o == nil || IsNil(o.ShippedSubscriptionUnits) {
		var ret float32
		return ret
	}
	return *o.ShippedSubscriptionUnits
}

// GetShippedSubscriptionUnitsOk returns a tuple with the ShippedSubscriptionUnits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsResponseMetric) GetShippedSubscriptionUnitsOk() (*float32, bool) {
	if o == nil || IsNil(o.ShippedSubscriptionUnits) {
		return nil, false
	}
	return o.ShippedSubscriptionUnits, true
}

// HasShippedSubscriptionUnits returns a boolean if a field has been set.
func (o *GetSellingPartnerMetricsResponseMetric) HasShippedSubscriptionUnits() bool {
	if o != nil && !IsNil(o.ShippedSubscriptionUnits) {
		return true
	}

	return false
}

// SetShippedSubscriptionUnits gets a reference to the given float32 and assigns it to the ShippedSubscriptionUnits field.
func (o *GetSellingPartnerMetricsResponseMetric) SetShippedSubscriptionUnits(v float32) {
	o.ShippedSubscriptionUnits = &v
}

// GetActiveSubscriptions returns the ActiveSubscriptions field value if set, zero value otherwise.
func (o *GetSellingPartnerMetricsResponseMetric) GetActiveSubscriptions() float32 {
	if o == nil || IsNil(o.ActiveSubscriptions) {
		var ret float32
		return ret
	}
	return *o.ActiveSubscriptions
}

// GetActiveSubscriptionsOk returns a tuple with the ActiveSubscriptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsResponseMetric) GetActiveSubscriptionsOk() (*float32, bool) {
	if o == nil || IsNil(o.ActiveSubscriptions) {
		return nil, false
	}
	return o.ActiveSubscriptions, true
}

// HasActiveSubscriptions returns a boolean if a field has been set.
func (o *GetSellingPartnerMetricsResponseMetric) HasActiveSubscriptions() bool {
	if o != nil && !IsNil(o.ActiveSubscriptions) {
		return true
	}

	return false
}

// SetActiveSubscriptions gets a reference to the given float32 and assigns it to the ActiveSubscriptions field.
func (o *GetSellingPartnerMetricsResponseMetric) SetActiveSubscriptions(v float32) {
	o.ActiveSubscriptions = &v
}

// GetSubscriberAverageRevenue returns the SubscriberAverageRevenue field value if set, zero value otherwise.
func (o *GetSellingPartnerMetricsResponseMetric) GetSubscriberAverageRevenue() float64 {
	if o == nil || IsNil(o.SubscriberAverageRevenue) {
		var ret float64
		return ret
	}
	return *o.SubscriberAverageRevenue
}

// GetSubscriberAverageRevenueOk returns a tuple with the SubscriberAverageRevenue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsResponseMetric) GetSubscriberAverageRevenueOk() (*float64, bool) {
	if o == nil || IsNil(o.SubscriberAverageRevenue) {
		return nil, false
	}
	return o.SubscriberAverageRevenue, true
}

// HasSubscriberAverageRevenue returns a boolean if a field has been set.
func (o *GetSellingPartnerMetricsResponseMetric) HasSubscriberAverageRevenue() bool {
	if o != nil && !IsNil(o.SubscriberAverageRevenue) {
		return true
	}

	return false
}

// SetSubscriberAverageRevenue gets a reference to the given float64 and assigns it to the SubscriberAverageRevenue field.
func (o *GetSellingPartnerMetricsResponseMetric) SetSubscriberAverageRevenue(v float64) {
	o.SubscriberAverageRevenue = &v
}

// GetNonSubscriberAverageRevenue returns the NonSubscriberAverageRevenue field value if set, zero value otherwise.
func (o *GetSellingPartnerMetricsResponseMetric) GetNonSubscriberAverageRevenue() float64 {
	if o == nil || IsNil(o.NonSubscriberAverageRevenue) {
		var ret float64
		return ret
	}
	return *o.NonSubscriberAverageRevenue
}

// GetNonSubscriberAverageRevenueOk returns a tuple with the NonSubscriberAverageRevenue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsResponseMetric) GetNonSubscriberAverageRevenueOk() (*float64, bool) {
	if o == nil || IsNil(o.NonSubscriberAverageRevenue) {
		return nil, false
	}
	return o.NonSubscriberAverageRevenue, true
}

// HasNonSubscriberAverageRevenue returns a boolean if a field has been set.
func (o *GetSellingPartnerMetricsResponseMetric) HasNonSubscriberAverageRevenue() bool {
	if o != nil && !IsNil(o.NonSubscriberAverageRevenue) {
		return true
	}

	return false
}

// SetNonSubscriberAverageRevenue gets a reference to the given float64 and assigns it to the NonSubscriberAverageRevenue field.
func (o *GetSellingPartnerMetricsResponseMetric) SetNonSubscriberAverageRevenue(v float64) {
	o.NonSubscriberAverageRevenue = &v
}

// GetLostRevenueDueToOOS returns the LostRevenueDueToOOS field value if set, zero value otherwise.
func (o *GetSellingPartnerMetricsResponseMetric) GetLostRevenueDueToOOS() float64 {
	if o == nil || IsNil(o.LostRevenueDueToOOS) {
		var ret float64
		return ret
	}
	return *o.LostRevenueDueToOOS
}

// GetLostRevenueDueToOOSOk returns a tuple with the LostRevenueDueToOOS field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsResponseMetric) GetLostRevenueDueToOOSOk() (*float64, bool) {
	if o == nil || IsNil(o.LostRevenueDueToOOS) {
		return nil, false
	}
	return o.LostRevenueDueToOOS, true
}

// HasLostRevenueDueToOOS returns a boolean if a field has been set.
func (o *GetSellingPartnerMetricsResponseMetric) HasLostRevenueDueToOOS() bool {
	if o != nil && !IsNil(o.LostRevenueDueToOOS) {
		return true
	}

	return false
}

// SetLostRevenueDueToOOS gets a reference to the given float64 and assigns it to the LostRevenueDueToOOS field.
func (o *GetSellingPartnerMetricsResponseMetric) SetLostRevenueDueToOOS(v float64) {
	o.LostRevenueDueToOOS = &v
}

// GetSubscriberAverageReorders returns the SubscriberAverageReorders field value if set, zero value otherwise.
func (o *GetSellingPartnerMetricsResponseMetric) GetSubscriberAverageReorders() float64 {
	if o == nil || IsNil(o.SubscriberAverageReorders) {
		var ret float64
		return ret
	}
	return *o.SubscriberAverageReorders
}

// GetSubscriberAverageReordersOk returns a tuple with the SubscriberAverageReorders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsResponseMetric) GetSubscriberAverageReordersOk() (*float64, bool) {
	if o == nil || IsNil(o.SubscriberAverageReorders) {
		return nil, false
	}
	return o.SubscriberAverageReorders, true
}

// HasSubscriberAverageReorders returns a boolean if a field has been set.
func (o *GetSellingPartnerMetricsResponseMetric) HasSubscriberAverageReorders() bool {
	if o != nil && !IsNil(o.SubscriberAverageReorders) {
		return true
	}

	return false
}

// SetSubscriberAverageReorders gets a reference to the given float64 and assigns it to the SubscriberAverageReorders field.
func (o *GetSellingPartnerMetricsResponseMetric) SetSubscriberAverageReorders(v float64) {
	o.SubscriberAverageReorders = &v
}

// GetNonSubscriberAverageReorders returns the NonSubscriberAverageReorders field value if set, zero value otherwise.
func (o *GetSellingPartnerMetricsResponseMetric) GetNonSubscriberAverageReorders() float64 {
	if o == nil || IsNil(o.NonSubscriberAverageReorders) {
		var ret float64
		return ret
	}
	return *o.NonSubscriberAverageReorders
}

// GetNonSubscriberAverageReordersOk returns a tuple with the NonSubscriberAverageReorders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsResponseMetric) GetNonSubscriberAverageReordersOk() (*float64, bool) {
	if o == nil || IsNil(o.NonSubscriberAverageReorders) {
		return nil, false
	}
	return o.NonSubscriberAverageReorders, true
}

// HasNonSubscriberAverageReorders returns a boolean if a field has been set.
func (o *GetSellingPartnerMetricsResponseMetric) HasNonSubscriberAverageReorders() bool {
	if o != nil && !IsNil(o.NonSubscriberAverageReorders) {
		return true
	}

	return false
}

// SetNonSubscriberAverageReorders gets a reference to the given float64 and assigns it to the NonSubscriberAverageReorders field.
func (o *GetSellingPartnerMetricsResponseMetric) SetNonSubscriberAverageReorders(v float64) {
	o.NonSubscriberAverageReorders = &v
}

// GetCouponsRevenuePenetration returns the CouponsRevenuePenetration field value if set, zero value otherwise.
func (o *GetSellingPartnerMetricsResponseMetric) GetCouponsRevenuePenetration() float64 {
	if o == nil || IsNil(o.CouponsRevenuePenetration) {
		var ret float64
		return ret
	}
	return *o.CouponsRevenuePenetration
}

// GetCouponsRevenuePenetrationOk returns a tuple with the CouponsRevenuePenetration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsResponseMetric) GetCouponsRevenuePenetrationOk() (*float64, bool) {
	if o == nil || IsNil(o.CouponsRevenuePenetration) {
		return nil, false
	}
	return o.CouponsRevenuePenetration, true
}

// HasCouponsRevenuePenetration returns a boolean if a field has been set.
func (o *GetSellingPartnerMetricsResponseMetric) HasCouponsRevenuePenetration() bool {
	if o != nil && !IsNil(o.CouponsRevenuePenetration) {
		return true
	}

	return false
}

// SetCouponsRevenuePenetration gets a reference to the given float64 and assigns it to the CouponsRevenuePenetration field.
func (o *GetSellingPartnerMetricsResponseMetric) SetCouponsRevenuePenetration(v float64) {
	o.CouponsRevenuePenetration = &v
}

// GetRevenueFromSubscriptionsWithMultipleDeliveries returns the RevenueFromSubscriptionsWithMultipleDeliveries field value if set, zero value otherwise.
func (o *GetSellingPartnerMetricsResponseMetric) GetRevenueFromSubscriptionsWithMultipleDeliveries() float64 {
	if o == nil || IsNil(o.RevenueFromSubscriptionsWithMultipleDeliveries) {
		var ret float64
		return ret
	}
	return *o.RevenueFromSubscriptionsWithMultipleDeliveries
}

// GetRevenueFromSubscriptionsWithMultipleDeliveriesOk returns a tuple with the RevenueFromSubscriptionsWithMultipleDeliveries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsResponseMetric) GetRevenueFromSubscriptionsWithMultipleDeliveriesOk() (*float64, bool) {
	if o == nil || IsNil(o.RevenueFromSubscriptionsWithMultipleDeliveries) {
		return nil, false
	}
	return o.RevenueFromSubscriptionsWithMultipleDeliveries, true
}

// HasRevenueFromSubscriptionsWithMultipleDeliveries returns a boolean if a field has been set.
func (o *GetSellingPartnerMetricsResponseMetric) HasRevenueFromSubscriptionsWithMultipleDeliveries() bool {
	if o != nil && !IsNil(o.RevenueFromSubscriptionsWithMultipleDeliveries) {
		return true
	}

	return false
}

// SetRevenueFromSubscriptionsWithMultipleDeliveries gets a reference to the given float64 and assigns it to the RevenueFromSubscriptionsWithMultipleDeliveries field.
func (o *GetSellingPartnerMetricsResponseMetric) SetRevenueFromSubscriptionsWithMultipleDeliveries(v float64) {
	o.RevenueFromSubscriptionsWithMultipleDeliveries = &v
}

// GetRevenueFromActiveSubscriptionsWithSingleDelivery returns the RevenueFromActiveSubscriptionsWithSingleDelivery field value if set, zero value otherwise.
func (o *GetSellingPartnerMetricsResponseMetric) GetRevenueFromActiveSubscriptionsWithSingleDelivery() float64 {
	if o == nil || IsNil(o.RevenueFromActiveSubscriptionsWithSingleDelivery) {
		var ret float64
		return ret
	}
	return *o.RevenueFromActiveSubscriptionsWithSingleDelivery
}

// GetRevenueFromActiveSubscriptionsWithSingleDeliveryOk returns a tuple with the RevenueFromActiveSubscriptionsWithSingleDelivery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsResponseMetric) GetRevenueFromActiveSubscriptionsWithSingleDeliveryOk() (*float64, bool) {
	if o == nil || IsNil(o.RevenueFromActiveSubscriptionsWithSingleDelivery) {
		return nil, false
	}
	return o.RevenueFromActiveSubscriptionsWithSingleDelivery, true
}

// HasRevenueFromActiveSubscriptionsWithSingleDelivery returns a boolean if a field has been set.
func (o *GetSellingPartnerMetricsResponseMetric) HasRevenueFromActiveSubscriptionsWithSingleDelivery() bool {
	if o != nil && !IsNil(o.RevenueFromActiveSubscriptionsWithSingleDelivery) {
		return true
	}

	return false
}

// SetRevenueFromActiveSubscriptionsWithSingleDelivery gets a reference to the given float64 and assigns it to the RevenueFromActiveSubscriptionsWithSingleDelivery field.
func (o *GetSellingPartnerMetricsResponseMetric) SetRevenueFromActiveSubscriptionsWithSingleDelivery(v float64) {
	o.RevenueFromActiveSubscriptionsWithSingleDelivery = &v
}

// GetRevenueFromCancelledSubscriptionsAfterSingleDelivery returns the RevenueFromCancelledSubscriptionsAfterSingleDelivery field value if set, zero value otherwise.
func (o *GetSellingPartnerMetricsResponseMetric) GetRevenueFromCancelledSubscriptionsAfterSingleDelivery() float64 {
	if o == nil || IsNil(o.RevenueFromCancelledSubscriptionsAfterSingleDelivery) {
		var ret float64
		return ret
	}
	return *o.RevenueFromCancelledSubscriptionsAfterSingleDelivery
}

// GetRevenueFromCancelledSubscriptionsAfterSingleDeliveryOk returns a tuple with the RevenueFromCancelledSubscriptionsAfterSingleDelivery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsResponseMetric) GetRevenueFromCancelledSubscriptionsAfterSingleDeliveryOk() (*float64, bool) {
	if o == nil || IsNil(o.RevenueFromCancelledSubscriptionsAfterSingleDelivery) {
		return nil, false
	}
	return o.RevenueFromCancelledSubscriptionsAfterSingleDelivery, true
}

// HasRevenueFromCancelledSubscriptionsAfterSingleDelivery returns a boolean if a field has been set.
func (o *GetSellingPartnerMetricsResponseMetric) HasRevenueFromCancelledSubscriptionsAfterSingleDelivery() bool {
	if o != nil && !IsNil(o.RevenueFromCancelledSubscriptionsAfterSingleDelivery) {
		return true
	}

	return false
}

// SetRevenueFromCancelledSubscriptionsAfterSingleDelivery gets a reference to the given float64 and assigns it to the RevenueFromCancelledSubscriptionsAfterSingleDelivery field.
func (o *GetSellingPartnerMetricsResponseMetric) SetRevenueFromCancelledSubscriptionsAfterSingleDelivery(v float64) {
	o.RevenueFromCancelledSubscriptionsAfterSingleDelivery = &v
}

// GetSubscriberRetentionFor30Days returns the SubscriberRetentionFor30Days field value if set, zero value otherwise.
func (o *GetSellingPartnerMetricsResponseMetric) GetSubscriberRetentionFor30Days() float64 {
	if o == nil || IsNil(o.SubscriberRetentionFor30Days) {
		var ret float64
		return ret
	}
	return *o.SubscriberRetentionFor30Days
}

// GetSubscriberRetentionFor30DaysOk returns a tuple with the SubscriberRetentionFor30Days field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsResponseMetric) GetSubscriberRetentionFor30DaysOk() (*float64, bool) {
	if o == nil || IsNil(o.SubscriberRetentionFor30Days) {
		return nil, false
	}
	return o.SubscriberRetentionFor30Days, true
}

// HasSubscriberRetentionFor30Days returns a boolean if a field has been set.
func (o *GetSellingPartnerMetricsResponseMetric) HasSubscriberRetentionFor30Days() bool {
	if o != nil && !IsNil(o.SubscriberRetentionFor30Days) {
		return true
	}

	return false
}

// SetSubscriberRetentionFor30Days gets a reference to the given float64 and assigns it to the SubscriberRetentionFor30Days field.
func (o *GetSellingPartnerMetricsResponseMetric) SetSubscriberRetentionFor30Days(v float64) {
	o.SubscriberRetentionFor30Days = &v
}

// GetSubscriberRetentionFor90Days returns the SubscriberRetentionFor90Days field value if set, zero value otherwise.
func (o *GetSellingPartnerMetricsResponseMetric) GetSubscriberRetentionFor90Days() float64 {
	if o == nil || IsNil(o.SubscriberRetentionFor90Days) {
		var ret float64
		return ret
	}
	return *o.SubscriberRetentionFor90Days
}

// GetSubscriberRetentionFor90DaysOk returns a tuple with the SubscriberRetentionFor90Days field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsResponseMetric) GetSubscriberRetentionFor90DaysOk() (*float64, bool) {
	if o == nil || IsNil(o.SubscriberRetentionFor90Days) {
		return nil, false
	}
	return o.SubscriberRetentionFor90Days, true
}

// HasSubscriberRetentionFor90Days returns a boolean if a field has been set.
func (o *GetSellingPartnerMetricsResponseMetric) HasSubscriberRetentionFor90Days() bool {
	if o != nil && !IsNil(o.SubscriberRetentionFor90Days) {
		return true
	}

	return false
}

// SetSubscriberRetentionFor90Days gets a reference to the given float64 and assigns it to the SubscriberRetentionFor90Days field.
func (o *GetSellingPartnerMetricsResponseMetric) SetSubscriberRetentionFor90Days(v float64) {
	o.SubscriberRetentionFor90Days = &v
}

// GetRevenuePenetrationFor0PercentSellerFunding returns the RevenuePenetrationFor0PercentSellerFunding field value if set, zero value otherwise.
func (o *GetSellingPartnerMetricsResponseMetric) GetRevenuePenetrationFor0PercentSellerFunding() float64 {
	if o == nil || IsNil(o.RevenuePenetrationFor0PercentSellerFunding) {
		var ret float64
		return ret
	}
	return *o.RevenuePenetrationFor0PercentSellerFunding
}

// GetRevenuePenetrationFor0PercentSellerFundingOk returns a tuple with the RevenuePenetrationFor0PercentSellerFunding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsResponseMetric) GetRevenuePenetrationFor0PercentSellerFundingOk() (*float64, bool) {
	if o == nil || IsNil(o.RevenuePenetrationFor0PercentSellerFunding) {
		return nil, false
	}
	return o.RevenuePenetrationFor0PercentSellerFunding, true
}

// HasRevenuePenetrationFor0PercentSellerFunding returns a boolean if a field has been set.
func (o *GetSellingPartnerMetricsResponseMetric) HasRevenuePenetrationFor0PercentSellerFunding() bool {
	if o != nil && !IsNil(o.RevenuePenetrationFor0PercentSellerFunding) {
		return true
	}

	return false
}

// SetRevenuePenetrationFor0PercentSellerFunding gets a reference to the given float64 and assigns it to the RevenuePenetrationFor0PercentSellerFunding field.
func (o *GetSellingPartnerMetricsResponseMetric) SetRevenuePenetrationFor0PercentSellerFunding(v float64) {
	o.RevenuePenetrationFor0PercentSellerFunding = &v
}

// GetRevenuePenetrationFor5PercentSellerFunding returns the RevenuePenetrationFor5PercentSellerFunding field value if set, zero value otherwise.
func (o *GetSellingPartnerMetricsResponseMetric) GetRevenuePenetrationFor5PercentSellerFunding() float64 {
	if o == nil || IsNil(o.RevenuePenetrationFor5PercentSellerFunding) {
		var ret float64
		return ret
	}
	return *o.RevenuePenetrationFor5PercentSellerFunding
}

// GetRevenuePenetrationFor5PercentSellerFundingOk returns a tuple with the RevenuePenetrationFor5PercentSellerFunding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsResponseMetric) GetRevenuePenetrationFor5PercentSellerFundingOk() (*float64, bool) {
	if o == nil || IsNil(o.RevenuePenetrationFor5PercentSellerFunding) {
		return nil, false
	}
	return o.RevenuePenetrationFor5PercentSellerFunding, true
}

// HasRevenuePenetrationFor5PercentSellerFunding returns a boolean if a field has been set.
func (o *GetSellingPartnerMetricsResponseMetric) HasRevenuePenetrationFor5PercentSellerFunding() bool {
	if o != nil && !IsNil(o.RevenuePenetrationFor5PercentSellerFunding) {
		return true
	}

	return false
}

// SetRevenuePenetrationFor5PercentSellerFunding gets a reference to the given float64 and assigns it to the RevenuePenetrationFor5PercentSellerFunding field.
func (o *GetSellingPartnerMetricsResponseMetric) SetRevenuePenetrationFor5PercentSellerFunding(v float64) {
	o.RevenuePenetrationFor5PercentSellerFunding = &v
}

// GetRevenuePenetrationFor10PercentSellerFunding returns the RevenuePenetrationFor10PercentSellerFunding field value if set, zero value otherwise.
func (o *GetSellingPartnerMetricsResponseMetric) GetRevenuePenetrationFor10PercentSellerFunding() float64 {
	if o == nil || IsNil(o.RevenuePenetrationFor10PercentSellerFunding) {
		var ret float64
		return ret
	}
	return *o.RevenuePenetrationFor10PercentSellerFunding
}

// GetRevenuePenetrationFor10PercentSellerFundingOk returns a tuple with the RevenuePenetrationFor10PercentSellerFunding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsResponseMetric) GetRevenuePenetrationFor10PercentSellerFundingOk() (*float64, bool) {
	if o == nil || IsNil(o.RevenuePenetrationFor10PercentSellerFunding) {
		return nil, false
	}
	return o.RevenuePenetrationFor10PercentSellerFunding, true
}

// HasRevenuePenetrationFor10PercentSellerFunding returns a boolean if a field has been set.
func (o *GetSellingPartnerMetricsResponseMetric) HasRevenuePenetrationFor10PercentSellerFunding() bool {
	if o != nil && !IsNil(o.RevenuePenetrationFor10PercentSellerFunding) {
		return true
	}

	return false
}

// SetRevenuePenetrationFor10PercentSellerFunding gets a reference to the given float64 and assigns it to the RevenuePenetrationFor10PercentSellerFunding field.
func (o *GetSellingPartnerMetricsResponseMetric) SetRevenuePenetrationFor10PercentSellerFunding(v float64) {
	o.RevenuePenetrationFor10PercentSellerFunding = &v
}

// GetRevenuePenetrationFor5PlusPercentSellerFunding returns the RevenuePenetrationFor5PlusPercentSellerFunding field value if set, zero value otherwise.
func (o *GetSellingPartnerMetricsResponseMetric) GetRevenuePenetrationFor5PlusPercentSellerFunding() float64 {
	if o == nil || IsNil(o.RevenuePenetrationFor5PlusPercentSellerFunding) {
		var ret float64
		return ret
	}
	return *o.RevenuePenetrationFor5PlusPercentSellerFunding
}

// GetRevenuePenetrationFor5PlusPercentSellerFundingOk returns a tuple with the RevenuePenetrationFor5PlusPercentSellerFunding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsResponseMetric) GetRevenuePenetrationFor5PlusPercentSellerFundingOk() (*float64, bool) {
	if o == nil || IsNil(o.RevenuePenetrationFor5PlusPercentSellerFunding) {
		return nil, false
	}
	return o.RevenuePenetrationFor5PlusPercentSellerFunding, true
}

// HasRevenuePenetrationFor5PlusPercentSellerFunding returns a boolean if a field has been set.
func (o *GetSellingPartnerMetricsResponseMetric) HasRevenuePenetrationFor5PlusPercentSellerFunding() bool {
	if o != nil && !IsNil(o.RevenuePenetrationFor5PlusPercentSellerFunding) {
		return true
	}

	return false
}

// SetRevenuePenetrationFor5PlusPercentSellerFunding gets a reference to the given float64 and assigns it to the RevenuePenetrationFor5PlusPercentSellerFunding field.
func (o *GetSellingPartnerMetricsResponseMetric) SetRevenuePenetrationFor5PlusPercentSellerFunding(v float64) {
	o.RevenuePenetrationFor5PlusPercentSellerFunding = &v
}

// GetShareOfCouponSubscriptions returns the ShareOfCouponSubscriptions field value if set, zero value otherwise.
func (o *GetSellingPartnerMetricsResponseMetric) GetShareOfCouponSubscriptions() float64 {
	if o == nil || IsNil(o.ShareOfCouponSubscriptions) {
		var ret float64
		return ret
	}
	return *o.ShareOfCouponSubscriptions
}

// GetShareOfCouponSubscriptionsOk returns a tuple with the ShareOfCouponSubscriptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsResponseMetric) GetShareOfCouponSubscriptionsOk() (*float64, bool) {
	if o == nil || IsNil(o.ShareOfCouponSubscriptions) {
		return nil, false
	}
	return o.ShareOfCouponSubscriptions, true
}

// HasShareOfCouponSubscriptions returns a boolean if a field has been set.
func (o *GetSellingPartnerMetricsResponseMetric) HasShareOfCouponSubscriptions() bool {
	if o != nil && !IsNil(o.ShareOfCouponSubscriptions) {
		return true
	}

	return false
}

// SetShareOfCouponSubscriptions gets a reference to the given float64 and assigns it to the ShareOfCouponSubscriptions field.
func (o *GetSellingPartnerMetricsResponseMetric) SetShareOfCouponSubscriptions(v float64) {
	o.ShareOfCouponSubscriptions = &v
}

// GetTimeInterval returns the TimeInterval field value if set, zero value otherwise.
func (o *GetSellingPartnerMetricsResponseMetric) GetTimeInterval() TimeInterval {
	if o == nil || IsNil(o.TimeInterval) {
		var ret TimeInterval
		return ret
	}
	return *o.TimeInterval
}

// GetTimeIntervalOk returns a tuple with the TimeInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsResponseMetric) GetTimeIntervalOk() (*TimeInterval, bool) {
	if o == nil || IsNil(o.TimeInterval) {
		return nil, false
	}
	return o.TimeInterval, true
}

// HasTimeInterval returns a boolean if a field has been set.
func (o *GetSellingPartnerMetricsResponseMetric) HasTimeInterval() bool {
	if o != nil && !IsNil(o.TimeInterval) {
		return true
	}

	return false
}

// SetTimeInterval gets a reference to the given TimeInterval and assigns it to the TimeInterval field.
func (o *GetSellingPartnerMetricsResponseMetric) SetTimeInterval(v TimeInterval) {
	o.TimeInterval = &v
}

// GetCurrencyCode returns the CurrencyCode field value if set, zero value otherwise.
func (o *GetSellingPartnerMetricsResponseMetric) GetCurrencyCode() string {
	if o == nil || IsNil(o.CurrencyCode) {
		var ret string
		return ret
	}
	return *o.CurrencyCode
}

// GetCurrencyCodeOk returns a tuple with the CurrencyCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSellingPartnerMetricsResponseMetric) GetCurrencyCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CurrencyCode) {
		return nil, false
	}
	return o.CurrencyCode, true
}

// HasCurrencyCode returns a boolean if a field has been set.
func (o *GetSellingPartnerMetricsResponseMetric) HasCurrencyCode() bool {
	if o != nil && !IsNil(o.CurrencyCode) {
		return true
	}

	return false
}

// SetCurrencyCode gets a reference to the given string and assigns it to the CurrencyCode field.
func (o *GetSellingPartnerMetricsResponseMetric) SetCurrencyCode(v string) {
	o.CurrencyCode = &v
}

func (o GetSellingPartnerMetricsResponseMetric) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NotDeliveredDueToOOS) {
		toSerialize["notDeliveredDueToOOS"] = o.NotDeliveredDueToOOS
	}
	if !IsNil(o.TotalSubscriptionsRevenue) {
		toSerialize["totalSubscriptionsRevenue"] = o.TotalSubscriptionsRevenue
	}
	if !IsNil(o.ShippedSubscriptionUnits) {
		toSerialize["shippedSubscriptionUnits"] = o.ShippedSubscriptionUnits
	}
	if !IsNil(o.ActiveSubscriptions) {
		toSerialize["activeSubscriptions"] = o.ActiveSubscriptions
	}
	if !IsNil(o.SubscriberAverageRevenue) {
		toSerialize["subscriberAverageRevenue"] = o.SubscriberAverageRevenue
	}
	if !IsNil(o.NonSubscriberAverageRevenue) {
		toSerialize["nonSubscriberAverageRevenue"] = o.NonSubscriberAverageRevenue
	}
	if !IsNil(o.LostRevenueDueToOOS) {
		toSerialize["lostRevenueDueToOOS"] = o.LostRevenueDueToOOS
	}
	if !IsNil(o.SubscriberAverageReorders) {
		toSerialize["subscriberAverageReorders"] = o.SubscriberAverageReorders
	}
	if !IsNil(o.NonSubscriberAverageReorders) {
		toSerialize["nonSubscriberAverageReorders"] = o.NonSubscriberAverageReorders
	}
	if !IsNil(o.CouponsRevenuePenetration) {
		toSerialize["couponsRevenuePenetration"] = o.CouponsRevenuePenetration
	}
	if !IsNil(o.RevenueFromSubscriptionsWithMultipleDeliveries) {
		toSerialize["revenueFromSubscriptionsWithMultipleDeliveries"] = o.RevenueFromSubscriptionsWithMultipleDeliveries
	}
	if !IsNil(o.RevenueFromActiveSubscriptionsWithSingleDelivery) {
		toSerialize["revenueFromActiveSubscriptionsWithSingleDelivery"] = o.RevenueFromActiveSubscriptionsWithSingleDelivery
	}
	if !IsNil(o.RevenueFromCancelledSubscriptionsAfterSingleDelivery) {
		toSerialize["revenueFromCancelledSubscriptionsAfterSingleDelivery"] = o.RevenueFromCancelledSubscriptionsAfterSingleDelivery
	}
	if !IsNil(o.SubscriberRetentionFor30Days) {
		toSerialize["subscriberRetentionFor30Days"] = o.SubscriberRetentionFor30Days
	}
	if !IsNil(o.SubscriberRetentionFor90Days) {
		toSerialize["subscriberRetentionFor90Days"] = o.SubscriberRetentionFor90Days
	}
	if !IsNil(o.RevenuePenetrationFor0PercentSellerFunding) {
		toSerialize["revenuePenetrationFor0PercentSellerFunding"] = o.RevenuePenetrationFor0PercentSellerFunding
	}
	if !IsNil(o.RevenuePenetrationFor5PercentSellerFunding) {
		toSerialize["revenuePenetrationFor5PercentSellerFunding"] = o.RevenuePenetrationFor5PercentSellerFunding
	}
	if !IsNil(o.RevenuePenetrationFor10PercentSellerFunding) {
		toSerialize["revenuePenetrationFor10PercentSellerFunding"] = o.RevenuePenetrationFor10PercentSellerFunding
	}
	if !IsNil(o.RevenuePenetrationFor5PlusPercentSellerFunding) {
		toSerialize["revenuePenetrationFor5PlusPercentSellerFunding"] = o.RevenuePenetrationFor5PlusPercentSellerFunding
	}
	if !IsNil(o.ShareOfCouponSubscriptions) {
		toSerialize["shareOfCouponSubscriptions"] = o.ShareOfCouponSubscriptions
	}
	if !IsNil(o.TimeInterval) {
		toSerialize["timeInterval"] = o.TimeInterval
	}
	if !IsNil(o.CurrencyCode) {
		toSerialize["currencyCode"] = o.CurrencyCode
	}
	return toSerialize, nil
}

type NullableGetSellingPartnerMetricsResponseMetric struct {
	value *GetSellingPartnerMetricsResponseMetric
	isSet bool
}

func (v NullableGetSellingPartnerMetricsResponseMetric) Get() *GetSellingPartnerMetricsResponseMetric {
	return v.value
}

func (v *NullableGetSellingPartnerMetricsResponseMetric) Set(val *GetSellingPartnerMetricsResponseMetric) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSellingPartnerMetricsResponseMetric) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSellingPartnerMetricsResponseMetric) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSellingPartnerMetricsResponseMetric(val *GetSellingPartnerMetricsResponseMetric) *NullableGetSellingPartnerMetricsResponseMetric {
	return &NullableGetSellingPartnerMetricsResponseMetric{value: val, isSet: true}
}

func (v NullableGetSellingPartnerMetricsResponseMetric) MarshalJSON() ([]byte, error) {
	return sonic.Marshal(v.value)
}

func (v *NullableGetSellingPartnerMetricsResponseMetric) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return sonic.Unmarshal(src, &v.value)
}
