package sp_v3

import (
	"github.com/bytedance/sonic"
)

// checks if the SponsoredProductsNewCampaignDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SponsoredProductsNewCampaignDetails{}

// SponsoredProductsNewCampaignDetails The request object for creating a new target promotion group with new campaigns.
type SponsoredProductsNewCampaignDetails struct {
	// The end date of the new target promotion group entities. The format of the date is YYYY-MM-DD.
	EndDate *string `json:"endDate,omitempty"`
	// The name prefix to be used for the entities under the target promotion group. e.g. if the namePrefix     is ABC, we will create a keyword campaign with the name 'ABC-ManualKeywordTargeting-Campaign-AutoGenerated'
	NamePrefix     string                                      `json:"namePrefix"`
	DynamicBidding *SponsoredProductsNewCampaignDynamicBidding `json:"dynamicBidding,omitempty"`
	// The start date of the new target promotion group entities. Default is today's date. The format of the date is YYYY-MM-DD.
	StartDate *string `json:"startDate,omitempty"`
	// The default bid value that gets applied if no bid is provided for the target. For more information about bid constraints by marketplace, see [bid limits](https://advertising.amazon.com/API/docs/en-us/concepts/limits#bid-constraints-by-marketplace).
	DefaultBid float64                            `json:"defaultBid"`
	Budget     SponsoredProductsNewCampaignBudget `json:"budget"`
	// A list of advertiser-specified custom identifiers for the campaign. Each customer identifier is a key-value pair. You can specify a maximum of 50 identifiers.
	Tags *map[string]string `json:"tags,omitempty"`
}

type _SponsoredProductsNewCampaignDetails SponsoredProductsNewCampaignDetails

// NewSponsoredProductsNewCampaignDetails instantiates a new SponsoredProductsNewCampaignDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSponsoredProductsNewCampaignDetails(namePrefix string, defaultBid float64, budget SponsoredProductsNewCampaignBudget) *SponsoredProductsNewCampaignDetails {
	this := SponsoredProductsNewCampaignDetails{}
	this.NamePrefix = namePrefix
	this.DefaultBid = defaultBid
	this.Budget = budget
	return &this
}

// NewSponsoredProductsNewCampaignDetailsWithDefaults instantiates a new SponsoredProductsNewCampaignDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSponsoredProductsNewCampaignDetailsWithDefaults() *SponsoredProductsNewCampaignDetails {
	this := SponsoredProductsNewCampaignDetails{}
	return &this
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *SponsoredProductsNewCampaignDetails) GetEndDate() string {
	if o == nil || IsNil(o.EndDate) {
		var ret string
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SponsoredProductsNewCampaignDetails) GetEndDateOk() (*string, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *SponsoredProductsNewCampaignDetails) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given string and assigns it to the EndDate field.
func (o *SponsoredProductsNewCampaignDetails) SetEndDate(v string) {
	o.EndDate = &v
}

// GetNamePrefix returns the NamePrefix field value
func (o *SponsoredProductsNewCampaignDetails) GetNamePrefix() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NamePrefix
}

// GetNamePrefixOk returns a tuple with the NamePrefix field value
// and a boolean to check if the value has been set.
func (o *SponsoredProductsNewCampaignDetails) GetNamePrefixOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NamePrefix, true
}

// SetNamePrefix sets field value
func (o *SponsoredProductsNewCampaignDetails) SetNamePrefix(v string) {
	o.NamePrefix = v
}

// GetDynamicBidding returns the DynamicBidding field value if set, zero value otherwise.
func (o *SponsoredProductsNewCampaignDetails) GetDynamicBidding() SponsoredProductsNewCampaignDynamicBidding {
	if o == nil || IsNil(o.DynamicBidding) {
		var ret SponsoredProductsNewCampaignDynamicBidding
		return ret
	}
	return *o.DynamicBidding
}

// GetDynamicBiddingOk returns a tuple with the DynamicBidding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SponsoredProductsNewCampaignDetails) GetDynamicBiddingOk() (*SponsoredProductsNewCampaignDynamicBidding, bool) {
	if o == nil || IsNil(o.DynamicBidding) {
		return nil, false
	}
	return o.DynamicBidding, true
}

// HasDynamicBidding returns a boolean if a field has been set.
func (o *SponsoredProductsNewCampaignDetails) HasDynamicBidding() bool {
	if o != nil && !IsNil(o.DynamicBidding) {
		return true
	}

	return false
}

// SetDynamicBidding gets a reference to the given SponsoredProductsNewCampaignDynamicBidding and assigns it to the DynamicBidding field.
func (o *SponsoredProductsNewCampaignDetails) SetDynamicBidding(v SponsoredProductsNewCampaignDynamicBidding) {
	o.DynamicBidding = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *SponsoredProductsNewCampaignDetails) GetStartDate() string {
	if o == nil || IsNil(o.StartDate) {
		var ret string
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SponsoredProductsNewCampaignDetails) GetStartDateOk() (*string, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *SponsoredProductsNewCampaignDetails) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given string and assigns it to the StartDate field.
func (o *SponsoredProductsNewCampaignDetails) SetStartDate(v string) {
	o.StartDate = &v
}

// GetDefaultBid returns the DefaultBid field value
func (o *SponsoredProductsNewCampaignDetails) GetDefaultBid() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.DefaultBid
}

// GetDefaultBidOk returns a tuple with the DefaultBid field value
// and a boolean to check if the value has been set.
func (o *SponsoredProductsNewCampaignDetails) GetDefaultBidOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultBid, true
}

// SetDefaultBid sets field value
func (o *SponsoredProductsNewCampaignDetails) SetDefaultBid(v float64) {
	o.DefaultBid = v
}

// GetBudget returns the Budget field value
func (o *SponsoredProductsNewCampaignDetails) GetBudget() SponsoredProductsNewCampaignBudget {
	if o == nil {
		var ret SponsoredProductsNewCampaignBudget
		return ret
	}

	return o.Budget
}

// GetBudgetOk returns a tuple with the Budget field value
// and a boolean to check if the value has been set.
func (o *SponsoredProductsNewCampaignDetails) GetBudgetOk() (*SponsoredProductsNewCampaignBudget, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Budget, true
}

// SetBudget sets field value
func (o *SponsoredProductsNewCampaignDetails) SetBudget(v SponsoredProductsNewCampaignBudget) {
	o.Budget = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *SponsoredProductsNewCampaignDetails) GetTags() map[string]string {
	if o == nil || IsNil(o.Tags) {
		var ret map[string]string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SponsoredProductsNewCampaignDetails) GetTagsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *SponsoredProductsNewCampaignDetails) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given map[string]string and assigns it to the Tags field.
func (o *SponsoredProductsNewCampaignDetails) SetTags(v map[string]string) {
	o.Tags = &v
}

func (o SponsoredProductsNewCampaignDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EndDate) {
		toSerialize["endDate"] = o.EndDate
	}
	toSerialize["namePrefix"] = o.NamePrefix
	if !IsNil(o.DynamicBidding) {
		toSerialize["dynamicBidding"] = o.DynamicBidding
	}
	if !IsNil(o.StartDate) {
		toSerialize["startDate"] = o.StartDate
	}
	toSerialize["defaultBid"] = o.DefaultBid
	toSerialize["budget"] = o.Budget
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	return toSerialize, nil
}

type NullableSponsoredProductsNewCampaignDetails struct {
	value *SponsoredProductsNewCampaignDetails
	isSet bool
}

func (v NullableSponsoredProductsNewCampaignDetails) Get() *SponsoredProductsNewCampaignDetails {
	return v.value
}

func (v *NullableSponsoredProductsNewCampaignDetails) Set(val *SponsoredProductsNewCampaignDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableSponsoredProductsNewCampaignDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableSponsoredProductsNewCampaignDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSponsoredProductsNewCampaignDetails(val *SponsoredProductsNewCampaignDetails) *NullableSponsoredProductsNewCampaignDetails {
	return &NullableSponsoredProductsNewCampaignDetails{value: val, isSet: true}
}

func (v NullableSponsoredProductsNewCampaignDetails) MarshalJSON() ([]byte, error) {
	return sonic.Marshal(v.value)
}

func (v *NullableSponsoredProductsNewCampaignDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return sonic.Unmarshal(src, &v.value)
}
