package sp_v3

import (
	"fmt"

	"github.com/bytedance/sonic"
)

// SponsoredProductsAdServingStatusReason the model 'SponsoredProductsAdServingStatusReason'
type SponsoredProductsAdServingStatusReason string

// List of SponsoredProductsAdServingStatusReason
const (
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_AD_GROUP_STATUS_ENABLED_DETAIL                  SponsoredProductsAdServingStatusReason = "AD_GROUP_STATUS_ENABLED_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_AD_GROUP_PAUSED_DETAIL                          SponsoredProductsAdServingStatusReason = "AD_GROUP_PAUSED_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_AD_GROUP_ARCHIVED_DETAIL                        SponsoredProductsAdServingStatusReason = "AD_GROUP_ARCHIVED_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_AD_GROUP_INCOMPLETE_DETAIL                      SponsoredProductsAdServingStatusReason = "AD_GROUP_INCOMPLETE_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_AD_GROUP_POLICING_PENDING_REVIEW_DETAIL         SponsoredProductsAdServingStatusReason = "AD_GROUP_POLICING_PENDING_REVIEW_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_AD_GROUP_POLICING_CREATIVE_REJECTED_DETAIL      SponsoredProductsAdServingStatusReason = "AD_GROUP_POLICING_CREATIVE_REJECTED_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_AD_GROUP_LOW_BID_DETAIL                         SponsoredProductsAdServingStatusReason = "AD_GROUP_LOW_BID_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_CAMPAIGN_STATUS_ENABLED_DETAIL                  SponsoredProductsAdServingStatusReason = "CAMPAIGN_STATUS_ENABLED_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_CAMPAIGN_PAUSED_DETAIL                          SponsoredProductsAdServingStatusReason = "CAMPAIGN_PAUSED_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_CAMPAIGN_ARCHIVED_DETAIL                        SponsoredProductsAdServingStatusReason = "CAMPAIGN_ARCHIVED_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_PENDING_REVIEW_DETAIL                           SponsoredProductsAdServingStatusReason = "PENDING_REVIEW_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_REJECTED_DETAIL                                 SponsoredProductsAdServingStatusReason = "REJECTED_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_PENDING_START_DATE_DETAIL                       SponsoredProductsAdServingStatusReason = "PENDING_START_DATE_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_ENDED_DETAIL                                    SponsoredProductsAdServingStatusReason = "ENDED_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_CAMPAIGN_OUT_OF_BUDGET_DETAIL                   SponsoredProductsAdServingStatusReason = "CAMPAIGN_OUT_OF_BUDGET_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_CAMPAIGN_INCOMPLETE_DETAIL                      SponsoredProductsAdServingStatusReason = "CAMPAIGN_INCOMPLETE_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_PORTFOLIO_STATUS_ENABLED_DETAIL                 SponsoredProductsAdServingStatusReason = "PORTFOLIO_STATUS_ENABLED_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_PORTFOLIO_PAUSED_DETAIL                         SponsoredProductsAdServingStatusReason = "PORTFOLIO_PAUSED_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_PORTFOLIO_ARCHIVED_DETAIL                       SponsoredProductsAdServingStatusReason = "PORTFOLIO_ARCHIVED_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_PORTFOLIO_OUT_OF_BUDGET_DETAIL                  SponsoredProductsAdServingStatusReason = "PORTFOLIO_OUT_OF_BUDGET_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_PORTFOLIO_PENDING_START_DATE_DETAIL             SponsoredProductsAdServingStatusReason = "PORTFOLIO_PENDING_START_DATE_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_PORTFOLIO_ENDED_DETAIL                          SponsoredProductsAdServingStatusReason = "PORTFOLIO_ENDED_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_ADVERTISER_POLICING_SUSPENDED_DETAIL            SponsoredProductsAdServingStatusReason = "ADVERTISER_POLICING_SUSPENDED_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_ADVERTISER_POLICING_PENDING_REVIEW_DETAIL       SponsoredProductsAdServingStatusReason = "ADVERTISER_POLICING_PENDING_REVIEW_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_ADVERTISER_ARCHIVED_DETAIL                      SponsoredProductsAdServingStatusReason = "ADVERTISER_ARCHIVED_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_ADVERTISER_PAUSED_DETAIL                        SponsoredProductsAdServingStatusReason = "ADVERTISER_PAUSED_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_ADVERTISER_OUT_OF_BUDGET_DETAIL                 SponsoredProductsAdServingStatusReason = "ADVERTISER_OUT_OF_BUDGET_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_ADVERTISER_PAYMENT_FAILURE_DETAIL               SponsoredProductsAdServingStatusReason = "ADVERTISER_PAYMENT_FAILURE_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_AD_STATUS_LIVE_DETAIL                           SponsoredProductsAdServingStatusReason = "AD_STATUS_LIVE_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_AD_POLICING_PENDING_REVIEW                      SponsoredProductsAdServingStatusReason = "AD_POLICING_PENDING_REVIEW"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_AD_POLICING_SUSPENDED_DETAIL                    SponsoredProductsAdServingStatusReason = "AD_POLICING_SUSPENDED_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_AD_PAUSED_DETAIL                                SponsoredProductsAdServingStatusReason = "AD_PAUSED_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_AD_ARCHIVED_DETAIL                              SponsoredProductsAdServingStatusReason = "AD_ARCHIVED_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_MISSING_IMAGE_DETAIL                            SponsoredProductsAdServingStatusReason = "MISSING_IMAGE_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_MODERATION_ADULT_PRODUCT_PV_DETAIL              SponsoredProductsAdServingStatusReason = "MODERATION_ADULT_PRODUCT_PV_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_MODERATION_ADULT_NOVELTY_PV_DETAIL              SponsoredProductsAdServingStatusReason = "MODERATION_ADULT_NOVELTY_PV_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_MODERATION_ADULT_SOFTLINES_PV_DETAIL            SponsoredProductsAdServingStatusReason = "MODERATION_ADULT_SOFTLINES_PV_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_MODERATION_CONTENT_NUDITY_PV_DETAIL             SponsoredProductsAdServingStatusReason = "MODERATION_CONTENT_NUDITY_PV_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_MODERATION_CONTENT_PROVOCATIVE_PV_DETAIL        SponsoredProductsAdServingStatusReason = "MODERATION_CONTENT_PROVOCATIVE_PV_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_MODERATION_CLAIM_WEIGHTLOSS_PV_DETAIL           SponsoredProductsAdServingStatusReason = "MODERATION_CLAIM_WEIGHTLOSS_PV_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_MODERATION_ERROR_404_PV_DETAIL                  SponsoredProductsAdServingStatusReason = "MODERATION_ERROR_404_PV_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_MODERATION_GRAPHICAL_SEXUAL_IMAGES_PV_DETAIL    SponsoredProductsAdServingStatusReason = "MODERATION_GRAPHICAL_SEXUAL_IMAGES_PV_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_MODERATION_LANGUAGE_OFFENSIVE_PV_DETAIL         SponsoredProductsAdServingStatusReason = "MODERATION_LANGUAGE_OFFENSIVE_PV_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_MODERATION_HFSS_PRODUCT_PV_DETAIL               SponsoredProductsAdServingStatusReason = "MODERATION_HFSS_PRODUCT_PV_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_MODERATION_CONTENT_SMOKING_PV_DETAIL            SponsoredProductsAdServingStatusReason = "MODERATION_CONTENT_SMOKING_PV_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_MODERATION_SMOKING_RELATED_PV_DETAIL            SponsoredProductsAdServingStatusReason = "MODERATION_SMOKING_RELATED_PV_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_MODERATION_NOT_COMPLIANT_TO_AD_POLICY_PV_DETAIL SponsoredProductsAdServingStatusReason = "MODERATION_NOT_COMPLIANT_TO_AD_POLICY_PV_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_MODERATION_CRITICAL_EVENTS_PV_DETAIL            SponsoredProductsAdServingStatusReason = "MODERATION_CRITICAL_EVENTS_PV_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_ACCOUNT_OUT_OF_BUDGET_DETAIL                    SponsoredProductsAdServingStatusReason = "ACCOUNT_OUT_OF_BUDGET_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_ADVERTISER_ACCOUNT_OUT_OF_BUDGET_DETAIL         SponsoredProductsAdServingStatusReason = "ADVERTISER_ACCOUNT_OUT_OF_BUDGET_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_ADVERTISER_EXCEED_SPENDS_LIMIT_DETAIL           SponsoredProductsAdServingStatusReason = "ADVERTISER_EXCEED_SPENDS_LIMIT_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_ADVERTISER_STATUS_ENABLED_DETAIL                SponsoredProductsAdServingStatusReason = "ADVERTISER_STATUS_ENABLED_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_AD_CREATION_OFFLINE_FAILED                      SponsoredProductsAdServingStatusReason = "AD_CREATION_OFFLINE_FAILED"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_AD_CREATION_OFFLINE_IN_PROGRESS                 SponsoredProductsAdServingStatusReason = "AD_CREATION_OFFLINE_IN_PROGRESS"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_AD_CREATION_OFFLINE_PENDING                     SponsoredProductsAdServingStatusReason = "AD_CREATION_OFFLINE_PENDING"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_CAMPAIGN_ADS_NOT_DELIVERING_DETAIL              SponsoredProductsAdServingStatusReason = "CAMPAIGN_ADS_NOT_DELIVERING_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_LANDING_PAGE_NOT_AVAILABLE_DETAIL               SponsoredProductsAdServingStatusReason = "LANDING_PAGE_NOT_AVAILABLE_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_MISSING_DECORATION_DETAIL                       SponsoredProductsAdServingStatusReason = "MISSING_DECORATION_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_NOT_BUYABLE_DETAIL                              SponsoredProductsAdServingStatusReason = "NOT_BUYABLE_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_NOT_IN_BUYBOX_DETAIL                            SponsoredProductsAdServingStatusReason = "NOT_IN_BUYBOX_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_OUT_OF_STOCK_DETAIL                             SponsoredProductsAdServingStatusReason = "OUT_OF_STOCK_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_SECURITY_SCAN_PENDING_REVIEW                    SponsoredProductsAdServingStatusReason = "SECURITY_SCAN_PENDING_REVIEW"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_SECURITY_SCAN_REJECTED                          SponsoredProductsAdServingStatusReason = "SECURITY_SCAN_REJECTED"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_STATUS_UNAVAILABLE                              SponsoredProductsAdServingStatusReason = "STATUS_UNAVAILABLE"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_TARGETING_CLAUSE_ARCHIVED_DETAIL                SponsoredProductsAdServingStatusReason = "TARGETING_CLAUSE_ARCHIVED_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_TARGETING_CLAUSE_BLOCKED_DETAIL                 SponsoredProductsAdServingStatusReason = "TARGETING_CLAUSE_BLOCKED_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_TARGETING_CLAUSE_PAUSED_DETAIL                  SponsoredProductsAdServingStatusReason = "TARGETING_CLAUSE_PAUSED_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_TARGETING_CLAUSE_POLICING_SUSPENDED_DETAIL      SponsoredProductsAdServingStatusReason = "TARGETING_CLAUSE_POLICING_SUSPENDED_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_TARGETING_CLAUSE_STATUS_LIVE_DETAIL             SponsoredProductsAdServingStatusReason = "TARGETING_CLAUSE_STATUS_LIVE_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_ADULT_PRODUCT                                   SponsoredProductsAdServingStatusReason = "ADULT_PRODUCT"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_ASIN_QUARANTINED                                SponsoredProductsAdServingStatusReason = "ASIN_QUARANTINED"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_BRAND_REMOVED                                   SponsoredProductsAdServingStatusReason = "BRAND_REMOVED"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_CBA_NOT_SUPPORTED                               SponsoredProductsAdServingStatusReason = "CBA_NOT_SUPPORTED"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_CLOSED_GL                                       SponsoredProductsAdServingStatusReason = "CLOSED_GL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_CP_INELIGIBLE                                   SponsoredProductsAdServingStatusReason = "CP_INELIGIBLE"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_CP_INELIGIBLE_ASIN                              SponsoredProductsAdServingStatusReason = "CP_INELIGIBLE_ASIN"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_CP_INELIGIBLE_UNKNOWN                           SponsoredProductsAdServingStatusReason = "CP_INELIGIBLE_UNKNOWN"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_CP_INELIGIBLE_VENDOR                            SponsoredProductsAdServingStatusReason = "CP_INELIGIBLE_VENDOR"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_ELIGIBLE_DETAIL                                 SponsoredProductsAdServingStatusReason = "ELIGIBLE_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_INELIGIBLE_CONDITION                            SponsoredProductsAdServingStatusReason = "INELIGIBLE_CONDITION"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_INVENTORY_INCOMPLETE                            SponsoredProductsAdServingStatusReason = "INVENTORY_INCOMPLETE"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_ITEM_MISSING                                    SponsoredProductsAdServingStatusReason = "ITEM_MISSING"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_LANDING_PAGE_INELIGIBLE                         SponsoredProductsAdServingStatusReason = "LANDING_PAGE_INELIGIBLE"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_NO_INVENTORY_DETAIL                             SponsoredProductsAdServingStatusReason = "NO_INVENTORY_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_NO_PURCHASABLE_OFFER_DETAIL                     SponsoredProductsAdServingStatusReason = "NO_PURCHASABLE_OFFER_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_OFFER_MISSING_DETAIL                            SponsoredProductsAdServingStatusReason = "OFFER_MISSING_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_PIR_RULE_EXCLUDED                               SponsoredProductsAdServingStatusReason = "PIR_RULE_EXCLUDED"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_RESTRICTED_GL                                   SponsoredProductsAdServingStatusReason = "RESTRICTED_GL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_SKU_DEFECTIVE                                   SponsoredProductsAdServingStatusReason = "SKU_DEFECTIVE"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_VARIATION_PARENT                                SponsoredProductsAdServingStatusReason = "VARIATION_PARENT"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_AD_POLICING_PENDING_REVIEW_DETAIL               SponsoredProductsAdServingStatusReason = "AD_POLICING_PENDING_REVIEW_DETAIL"
	SPONSOREDPRODUCTSADSERVINGSTATUSREASON_OTHER                                           SponsoredProductsAdServingStatusReason = "OTHER"
)

// All allowed values of SponsoredProductsAdServingStatusReason enum
var AllowedSponsoredProductsAdServingStatusReasonEnumValues = []SponsoredProductsAdServingStatusReason{
	"AD_GROUP_STATUS_ENABLED_DETAIL",
	"AD_GROUP_PAUSED_DETAIL",
	"AD_GROUP_ARCHIVED_DETAIL",
	"AD_GROUP_INCOMPLETE_DETAIL",
	"AD_GROUP_POLICING_PENDING_REVIEW_DETAIL",
	"AD_GROUP_POLICING_CREATIVE_REJECTED_DETAIL",
	"AD_GROUP_LOW_BID_DETAIL",
	"CAMPAIGN_STATUS_ENABLED_DETAIL",
	"CAMPAIGN_PAUSED_DETAIL",
	"CAMPAIGN_ARCHIVED_DETAIL",
	"PENDING_REVIEW_DETAIL",
	"REJECTED_DETAIL",
	"PENDING_START_DATE_DETAIL",
	"ENDED_DETAIL",
	"CAMPAIGN_OUT_OF_BUDGET_DETAIL",
	"CAMPAIGN_INCOMPLETE_DETAIL",
	"PORTFOLIO_STATUS_ENABLED_DETAIL",
	"PORTFOLIO_PAUSED_DETAIL",
	"PORTFOLIO_ARCHIVED_DETAIL",
	"PORTFOLIO_OUT_OF_BUDGET_DETAIL",
	"PORTFOLIO_PENDING_START_DATE_DETAIL",
	"PORTFOLIO_ENDED_DETAIL",
	"ADVERTISER_POLICING_SUSPENDED_DETAIL",
	"ADVERTISER_POLICING_PENDING_REVIEW_DETAIL",
	"ADVERTISER_ARCHIVED_DETAIL",
	"ADVERTISER_PAUSED_DETAIL",
	"ADVERTISER_OUT_OF_BUDGET_DETAIL",
	"ADVERTISER_PAYMENT_FAILURE_DETAIL",
	"AD_STATUS_LIVE_DETAIL",
	"AD_POLICING_PENDING_REVIEW",
	"AD_POLICING_SUSPENDED_DETAIL",
	"AD_PAUSED_DETAIL",
	"AD_ARCHIVED_DETAIL",
	"MISSING_IMAGE_DETAIL",
	"MODERATION_ADULT_PRODUCT_PV_DETAIL",
	"MODERATION_ADULT_NOVELTY_PV_DETAIL",
	"MODERATION_ADULT_SOFTLINES_PV_DETAIL",
	"MODERATION_CONTENT_NUDITY_PV_DETAIL",
	"MODERATION_CONTENT_PROVOCATIVE_PV_DETAIL",
	"MODERATION_CLAIM_WEIGHTLOSS_PV_DETAIL",
	"MODERATION_ERROR_404_PV_DETAIL",
	"MODERATION_GRAPHICAL_SEXUAL_IMAGES_PV_DETAIL",
	"MODERATION_LANGUAGE_OFFENSIVE_PV_DETAIL",
	"MODERATION_HFSS_PRODUCT_PV_DETAIL",
	"MODERATION_CONTENT_SMOKING_PV_DETAIL",
	"MODERATION_SMOKING_RELATED_PV_DETAIL",
	"MODERATION_NOT_COMPLIANT_TO_AD_POLICY_PV_DETAIL",
	"MODERATION_CRITICAL_EVENTS_PV_DETAIL",
	"ACCOUNT_OUT_OF_BUDGET_DETAIL",
	"ADVERTISER_ACCOUNT_OUT_OF_BUDGET_DETAIL",
	"ADVERTISER_EXCEED_SPENDS_LIMIT_DETAIL",
	"ADVERTISER_STATUS_ENABLED_DETAIL",
	"AD_CREATION_OFFLINE_FAILED",
	"AD_CREATION_OFFLINE_IN_PROGRESS",
	"AD_CREATION_OFFLINE_PENDING",
	"CAMPAIGN_ADS_NOT_DELIVERING_DETAIL",
	"LANDING_PAGE_NOT_AVAILABLE_DETAIL",
	"MISSING_DECORATION_DETAIL",
	"NOT_BUYABLE_DETAIL",
	"NOT_IN_BUYBOX_DETAIL",
	"OUT_OF_STOCK_DETAIL",
	"SECURITY_SCAN_PENDING_REVIEW",
	"SECURITY_SCAN_REJECTED",
	"STATUS_UNAVAILABLE",
	"TARGETING_CLAUSE_ARCHIVED_DETAIL",
	"TARGETING_CLAUSE_BLOCKED_DETAIL",
	"TARGETING_CLAUSE_PAUSED_DETAIL",
	"TARGETING_CLAUSE_POLICING_SUSPENDED_DETAIL",
	"TARGETING_CLAUSE_STATUS_LIVE_DETAIL",
	"ADULT_PRODUCT",
	"ASIN_QUARANTINED",
	"BRAND_REMOVED",
	"CBA_NOT_SUPPORTED",
	"CLOSED_GL",
	"CP_INELIGIBLE",
	"CP_INELIGIBLE_ASIN",
	"CP_INELIGIBLE_UNKNOWN",
	"CP_INELIGIBLE_VENDOR",
	"ELIGIBLE_DETAIL",
	"INELIGIBLE_CONDITION",
	"INVENTORY_INCOMPLETE",
	"ITEM_MISSING",
	"LANDING_PAGE_INELIGIBLE",
	"NO_INVENTORY_DETAIL",
	"NO_PURCHASABLE_OFFER_DETAIL",
	"OFFER_MISSING_DETAIL",
	"PIR_RULE_EXCLUDED",
	"RESTRICTED_GL",
	"SKU_DEFECTIVE",
	"VARIATION_PARENT",
	"AD_POLICING_PENDING_REVIEW_DETAIL",
	"OTHER",
}

func (v *SponsoredProductsAdServingStatusReason) UnmarshalJSON(src []byte) error {
	var value string
	err := sonic.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SponsoredProductsAdServingStatusReason(value)
	for _, existing := range AllowedSponsoredProductsAdServingStatusReasonEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SponsoredProductsAdServingStatusReason", value)
}

// NewSponsoredProductsAdServingStatusReasonFromValue returns a pointer to a valid SponsoredProductsAdServingStatusReason
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSponsoredProductsAdServingStatusReasonFromValue(v string) (*SponsoredProductsAdServingStatusReason, error) {
	ev := SponsoredProductsAdServingStatusReason(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SponsoredProductsAdServingStatusReason: valid values are %v", v, AllowedSponsoredProductsAdServingStatusReasonEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SponsoredProductsAdServingStatusReason) IsValid() bool {
	for _, existing := range AllowedSponsoredProductsAdServingStatusReasonEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SponsoredProductsAdServingStatusReason value
func (v SponsoredProductsAdServingStatusReason) Ptr() *SponsoredProductsAdServingStatusReason {
	return &v
}

type NullableSponsoredProductsAdServingStatusReason struct {
	value *SponsoredProductsAdServingStatusReason
	isSet bool
}

func (v NullableSponsoredProductsAdServingStatusReason) Get() *SponsoredProductsAdServingStatusReason {
	return v.value
}

func (v *NullableSponsoredProductsAdServingStatusReason) Set(val *SponsoredProductsAdServingStatusReason) {
	v.value = val
	v.isSet = true
}

func (v NullableSponsoredProductsAdServingStatusReason) IsSet() bool {
	return v.isSet
}

func (v *NullableSponsoredProductsAdServingStatusReason) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSponsoredProductsAdServingStatusReason(val *SponsoredProductsAdServingStatusReason) *NullableSponsoredProductsAdServingStatusReason {
	return &NullableSponsoredProductsAdServingStatusReason{value: val, isSet: true}
}

func (v NullableSponsoredProductsAdServingStatusReason) MarshalJSON() ([]byte, error) {
	return sonic.Marshal(v.value)
}

func (v *NullableSponsoredProductsAdServingStatusReason) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return sonic.Unmarshal(src, &v.value)
}
