package sb_v4

import (
	"github.com/bytedance/sonic"
)

// checks if the SDHeadlineRecommendationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SDHeadlineRecommendationResponse{}

// SDHeadlineRecommendationResponse Response structure of SD headline recommendation API.
type SDHeadlineRecommendationResponse struct {
	// An identifier for request made which is generated by server.
	RequestId *string `json:"requestId,omitempty"`
	// Recommendations are sorted, i.e., more suitable headline has lesser array index value.
	Recommendations []RecommendedHeadline `json:"recommendations,omitempty"`
}

// NewSDHeadlineRecommendationResponse instantiates a new SDHeadlineRecommendationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSDHeadlineRecommendationResponse() *SDHeadlineRecommendationResponse {
	this := SDHeadlineRecommendationResponse{}
	return &this
}

// NewSDHeadlineRecommendationResponseWithDefaults instantiates a new SDHeadlineRecommendationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSDHeadlineRecommendationResponseWithDefaults() *SDHeadlineRecommendationResponse {
	this := SDHeadlineRecommendationResponse{}
	return &this
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *SDHeadlineRecommendationResponse) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SDHeadlineRecommendationResponse) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *SDHeadlineRecommendationResponse) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *SDHeadlineRecommendationResponse) SetRequestId(v string) {
	o.RequestId = &v
}

// GetRecommendations returns the Recommendations field value if set, zero value otherwise.
func (o *SDHeadlineRecommendationResponse) GetRecommendations() []RecommendedHeadline {
	if o == nil || IsNil(o.Recommendations) {
		var ret []RecommendedHeadline
		return ret
	}
	return o.Recommendations
}

// GetRecommendationsOk returns a tuple with the Recommendations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SDHeadlineRecommendationResponse) GetRecommendationsOk() ([]RecommendedHeadline, bool) {
	if o == nil || IsNil(o.Recommendations) {
		return nil, false
	}
	return o.Recommendations, true
}

// HasRecommendations returns a boolean if a field has been set.
func (o *SDHeadlineRecommendationResponse) HasRecommendations() bool {
	if o != nil && !IsNil(o.Recommendations) {
		return true
	}

	return false
}

// SetRecommendations gets a reference to the given []RecommendedHeadline and assigns it to the Recommendations field.
func (o *SDHeadlineRecommendationResponse) SetRecommendations(v []RecommendedHeadline) {
	o.Recommendations = v
}

func (o SDHeadlineRecommendationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	if !IsNil(o.Recommendations) {
		toSerialize["recommendations"] = o.Recommendations
	}
	return toSerialize, nil
}

type NullableSDHeadlineRecommendationResponse struct {
	value *SDHeadlineRecommendationResponse
	isSet bool
}

func (v NullableSDHeadlineRecommendationResponse) Get() *SDHeadlineRecommendationResponse {
	return v.value
}

func (v *NullableSDHeadlineRecommendationResponse) Set(val *SDHeadlineRecommendationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSDHeadlineRecommendationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSDHeadlineRecommendationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSDHeadlineRecommendationResponse(val *SDHeadlineRecommendationResponse) *NullableSDHeadlineRecommendationResponse {
	return &NullableSDHeadlineRecommendationResponse{value: val, isSet: true}
}

func (v NullableSDHeadlineRecommendationResponse) MarshalJSON() ([]byte, error) {
	return sonic.Marshal(v.value)
}

func (v *NullableSDHeadlineRecommendationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return sonic.Unmarshal(src, &v.value)
}
