package sb_v4

import (
	"github.com/bytedance/sonic"
)

// checks if the HeadlineSuggestionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HeadlineSuggestionResponse{}

// HeadlineSuggestionResponse Response structure of headline suggestion API.
type HeadlineSuggestionResponse struct {
	// An identifier for request made which is generated by server.
	RequestId *string `json:"requestId,omitempty"`
	// Suggestions are sorted, i.e., more suitable headline has lesser array index value
	Suggestions []SuggestedHeadline `json:"suggestions,omitempty"`
}

// NewHeadlineSuggestionResponse instantiates a new HeadlineSuggestionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHeadlineSuggestionResponse() *HeadlineSuggestionResponse {
	this := HeadlineSuggestionResponse{}
	return &this
}

// NewHeadlineSuggestionResponseWithDefaults instantiates a new HeadlineSuggestionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHeadlineSuggestionResponseWithDefaults() *HeadlineSuggestionResponse {
	this := HeadlineSuggestionResponse{}
	return &this
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *HeadlineSuggestionResponse) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HeadlineSuggestionResponse) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *HeadlineSuggestionResponse) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *HeadlineSuggestionResponse) SetRequestId(v string) {
	o.RequestId = &v
}

// GetSuggestions returns the Suggestions field value if set, zero value otherwise.
func (o *HeadlineSuggestionResponse) GetSuggestions() []SuggestedHeadline {
	if o == nil || IsNil(o.Suggestions) {
		var ret []SuggestedHeadline
		return ret
	}
	return o.Suggestions
}

// GetSuggestionsOk returns a tuple with the Suggestions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HeadlineSuggestionResponse) GetSuggestionsOk() ([]SuggestedHeadline, bool) {
	if o == nil || IsNil(o.Suggestions) {
		return nil, false
	}
	return o.Suggestions, true
}

// HasSuggestions returns a boolean if a field has been set.
func (o *HeadlineSuggestionResponse) HasSuggestions() bool {
	if o != nil && !IsNil(o.Suggestions) {
		return true
	}

	return false
}

// SetSuggestions gets a reference to the given []SuggestedHeadline and assigns it to the Suggestions field.
func (o *HeadlineSuggestionResponse) SetSuggestions(v []SuggestedHeadline) {
	o.Suggestions = v
}

func (o HeadlineSuggestionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	if !IsNil(o.Suggestions) {
		toSerialize["suggestions"] = o.Suggestions
	}
	return toSerialize, nil
}

type NullableHeadlineSuggestionResponse struct {
	value *HeadlineSuggestionResponse
	isSet bool
}

func (v NullableHeadlineSuggestionResponse) Get() *HeadlineSuggestionResponse {
	return v.value
}

func (v *NullableHeadlineSuggestionResponse) Set(val *HeadlineSuggestionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHeadlineSuggestionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHeadlineSuggestionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHeadlineSuggestionResponse(val *HeadlineSuggestionResponse) *NullableHeadlineSuggestionResponse {
	return &NullableHeadlineSuggestionResponse{value: val, isSet: true}
}

func (v NullableHeadlineSuggestionResponse) MarshalJSON() ([]byte, error) {
	return sonic.Marshal(v.value)
}

func (v *NullableHeadlineSuggestionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return sonic.Unmarshal(src, &v.value)
}
